version: "3.5"
services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /opt/mongodb/db:/data/db
    networks:
      - organic

  adminmongo:
    image: mrvautin/adminmongo
    ports:
      - "1234:1234"
    networks:
      - organic

  chrome:
    image: selenium/standalone-chrome-debug
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
      - "5900:5900"
    networks:
      - organic


networks:
  organic:
    driver: bridge
